#!/bin/make
#======================================================================
#		makefile
#======================================================================


#----------------------------------------------------------------------
#   Notes:
#
#	To add a new file to the system, simply list its source and
#	object files immediately below, then run 'make dep' --- this 
#	will make the new dependencies
#

#----------------------------------------------------------------------
#                       Name of the library
#----------------------------------------------------------------------
LIBNAME = libvsMotion.a

#----------------------------------------------------------------------
#			All Source and Object files
#----------------------------------------------------------------------
SRCS = \
       vs3TrackerArm.c++ \
       vsCollision.c++ \
       vsDrivingMotion.c++ \
       vsFlyingMotion.c++ \
       vsHeadMotion.c++ \
       vsKinematics.c++ \
       vsMotionModel.c++ \
       vsTerrainFollow.c++ \
       vsTrackballMotion.c++ \
       vsTrackedMotion.c++ \
       vsWalkInPlace.c++

OBJS = \
       vs3TrackerArm.o \
       vsCollision.o \
       vsDrivingMotion.o \
       vsFlyingMotion.o \
       vsHeadMotion.o \
       vsKinematics.o \
       vsMotionModel.o \
       vsTerrainFollow.o \
       vsTrackballMotion.o \
       vsTrackedMotion.o \
       vsWalkInPlace.o

#----------------------------------------------------------------------
#			Misc. settings
#----------------------------------------------------------------------
OS = IRIX

#----------------------------------------------------------------------
#			Compiler settings
#----------------------------------------------------------------------
CC = cc
CXX = CC
AR = ar
CFLAGS = -g -D$(OS) -n32 -mips3 -DSGI -xansi $(INCS)
CXXFLAGS = -g -D$(OS) -xansi -n32 -DSGI -mips3 $(INCS)
ARFLAGS = -rulc

#----------------------------------------------------------------------
#			Include file directories
#----------------------------------------------------------------------
include ../libpaths.IRIX

INCS = \
       -I../system \
       -I../scene \
       -I../math \
       -I../input \
       $(EXTRA_INCS)

#----------------------------------------------------------------------
#			Default target
#----------------------------------------------------------------------
all: $(LIBNAME)

#----------------------------------------------------------------------
#			Library archive rules
#----------------------------------------------------------------------
$(LIBNAME): $(OBJS)
	ar $(ARFLAGS) $(LIBNAME) $(OBJS)

#----------------------------------------------------------------------
#			Inference Rules
#----------------------------------------------------------------------
.c++.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

.c.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f core
	rm -f $(LIBNAME)
	rm -f makefile.*.bak

#----------------------------------------------------------------------
#			This is the dependency update rule
#----------------------------------------------------------------------
dep: depend
depend:
	makedepend -f makefile.IRIX -- $(CFLAGS) $(INCS) -- $(SRCS)

