#!/bin/make
#======================================================================
#		makefile
#======================================================================


#----------------------------------------------------------------------
#   Notes:
#
#	To add a new file to the system, simply list its source and
#	object files immediately below, then run 'make dep' --- this 
#	will make the new dependencies
#

#----------------------------------------------------------------------
#                       Name of the library
#----------------------------------------------------------------------
LIBNAME = libvsMotion.a

#----------------------------------------------------------------------
#			All Source and Object files
#----------------------------------------------------------------------
SRCS = \
       vs3TrackerArm.c++ \
       vsCollision.c++ \
       vsDrivingMotion.c++ \
       vsFlyingMotion.c++ \
       vsHeadMotion.c++ \
       vsKinematics.c++ \
       vsMotionModel.c++ \
       vsSphericalMotion.c++ \
       vsTerrainFollow.c++ \
       vsTrackballMotion.c++ \
       vsTrackedMotion.c++ \
       vsWalkArticulation.c++ \
       vsWalkInPlace.c++

OBJS = \
       vs3TrackerArm.o \
       vsCollision.o \
       vsDrivingMotion.o \
       vsFlyingMotion.o \
       vsHeadMotion.o \
       vsKinematics.o \
       vsMotionModel.o \
       vsSphericalMotion.o \
       vsTerrainFollow.o \
       vsTrackballMotion.o \
       vsTrackedMotion.o \
       vsWalkArticulation.o \
       vsWalkInPlace.o

#----------------------------------------------------------------------
#			Misc. settings
#----------------------------------------------------------------------
OS = LINUX

#----------------------------------------------------------------------
#			Compiler settings
#----------------------------------------------------------------------
CC = gcc
CXX = g++ 
AR = ar
CFLAGS = -g -O -D_XOPEN_SOURCE -D_BSD_SOURCE -D_MISC_SOURCE -D$(OS) -D__linux__ -ansi $(INCS)
CXXFLAGS = -g -O -D_XOPEN_SOURCE -D_BSD_SOURCE -D_MISC_SOURCE -D$(OS) -D__linux__ -ansi $(INCS)
ARFLAGS = -ruc

#----------------------------------------------------------------------
#			Include file directories
#----------------------------------------------------------------------
include ../libpaths.Linux

INCS = \
       -I.. \
       -I../scene \
       -I../math \
       -I../input \
       -I../system \
       -I/usr/include/g++-3 \
       -I/usr/include/g++-2 \
       -I/usr/X11R6/include \
       $(EXTRA_INCS)

#----------------------------------------------------------------------
#			Default target
#----------------------------------------------------------------------
all: $(LIBNAME)

#----------------------------------------------------------------------
#			Library archive rules
#----------------------------------------------------------------------
$(LIBNAME): $(OBJS)
	ar $(ARFLAGS) $(LIBNAME) $(OBJS)

#----------------------------------------------------------------------
#			Inference Rules
#----------------------------------------------------------------------
.SUFFIXES: .c .c++ .o .h .h++

.c++.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

.c.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f core
	rm -f $(LIBNAME)
	rm -f makefile.*.bak

#----------------------------------------------------------------------
#			This is the dependency update rule
#----------------------------------------------------------------------
dep: depend
depend:
	makedepend -f makefile.Linux -- $(CFLAGS) $(INCS) -- $(SRCS)

