#!/bin/make
#======================================================================
#		makefile
#======================================================================


#----------------------------------------------------------------------
#   Notes:
#
#	To add a new file to the system, simply list its source and
#	object files immediately below, then run 'make dep' --- this 
#	will make the new dependencies
#

#----------------------------------------------------------------------
#                       Name of the library
#----------------------------------------------------------------------
LIBNAME = libvsMotion.a

#----------------------------------------------------------------------
#			All Source and Object files
#----------------------------------------------------------------------
SRCS = \
       vsFlyingMotion.c++ \
       vsMotionModel.c++ \
       vsTrackballMotion.c++ \
       vsTrackedMotion.c++

OBJS = \
       vsFlyingMotion.o \
       vsMotionModel.o \
       vsTrackballMotion.o \
       vsTrackedMotion.o

#----------------------------------------------------------------------
#			Misc. settings
#----------------------------------------------------------------------
OS = IRIX64

#----------------------------------------------------------------------
#			Compiler settings
#----------------------------------------------------------------------
CC = cc
CXX = CC
AR = ar
CFLAGS = -g -D$(OS) -n32 -mips3 -DSGI -xansi $(INCS)
CXXFLAGS = -g -D$(OS) -xansi -n32 -DSGI -mips3 $(INCS)
ARFLAGS = -rulc

#----------------------------------------------------------------------
#			Include file directories
#----------------------------------------------------------------------
INCS = \
       -I../corelib \
       -I../scene \
       -I../math \
       -I../input

#----------------------------------------------------------------------
#			Linking Libraries - directories and libs
#----------------------------------------------------------------------
LDIRS = \
      -nostdlib \
      -L/usr/lib32/mips3 \
      -L/usr/lib32/internal \
      -L/usr/lib32/libpfdb \
      -L/usr/lib32

LLIBS = -ignore_unresolved \
	-lC \
	-lc \
	-lm

LIBS = $(LDIRS) $(LLIBS)

#----------------------------------------------------------------------
#			Default target
#----------------------------------------------------------------------
all: $(LIBNAME)

#----------------------------------------------------------------------
#			Library archive rules
#----------------------------------------------------------------------
$(LIBNAME): $(OBJS)
	ar $(ARFLAGS) $(LIBNAME) $(OBJS)

#----------------------------------------------------------------------
#			Inference Rules
#----------------------------------------------------------------------
.c++.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

.c.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f core
	rm -f $(LIBNAME)
	rm -f makefile.*.bak

#----------------------------------------------------------------------
#			This is the dependency update rule
#----------------------------------------------------------------------
dep: depend
depend:
	makedepend -f makefile.IRIX -- $(CFLAGS) $(INCS) -- $(SRCS)
#----------------------------------------------------------------------
# Our automatically generated dependencies follow...
# Please don't mess below this line
# DO NOT DELETE

vsFlyingMotion.o: vsFlyingMotion.h++ vsMotionModel.h++
vsFlyingMotion.o: ../corelib/vsGlobals.h++ ../math/vsVecQuat.h++
vsFlyingMotion.o: ../math/vsMatrix.h++ ../math/vsVector.h++
vsFlyingMotion.o: ../math/vsQuat.h++ ../scene/vsComponent.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfGroup.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfNode.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsFlyingMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsFlyingMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsFlyingMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsFlyingMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsFlyingMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsFlyingMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsFlyingMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsFlyingMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsFlyingMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsFlyingMotion.o: /usr/include/X11/Xutil.h
vsFlyingMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsFlyingMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsFlyingMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsFlyingMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsFlyingMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsFlyingMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsFlyingMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsFlyingMotion.o: /usr/include/Performer/opengl.h
vsFlyingMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsFlyingMotion.o: /usr/include/Performer/prstats.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfObject.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsFlyingMotion.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfStruct.h
vsFlyingMotion.o: /usr/include/Performer/pfstats.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfLists.h
vsFlyingMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsFlyingMotion.o: /usr/include/sys/cdefs.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfPipe.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfList.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfStats.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfDispList.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfState.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfSwitch.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfFlux.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfEngine.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfSequence.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfLOD.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfLODState.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfGeode.h ../corelib/vsSystem.h++
vsFlyingMotion.o: ../corelib/vsPipe.h++ ../corelib/vsScreen.h++
vsFlyingMotion.o: ../corelib/vsWindow.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfPipeWindow.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfWindow.h ../corelib/vsPane.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfChannel.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfPipeVideoChannel.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfEarthSky.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfScene.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfGeoSet.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfCycleBuffer.h
vsFlyingMotion.o: ../corelib/vsView.h++ ../scene/vsViewpointAttribute.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfSCS.h ../scene/vsNode.h++
vsFlyingMotion.o: ../scene/vsAttributeList.h++ ../scene/vsAttribute.h++
vsFlyingMotion.o: /usr/include/stdlib.h ../corelib/vsDatabaseLoader.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfBillboard.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfCuller.h /usr/include/alloca.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfTraverser.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfSprite.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfDCS.h
vsFlyingMotion.o: /usr/include/Performer/pfdu.h
vsFlyingMotion.o: /usr/include/Performer/pfutil.h /usr/include/dlfcn.h
vsFlyingMotion.o: /usr/include/Performer/objfnt.h
vsFlyingMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsFlyingMotion.o: ../corelib/vsObjectMap.h++
vsFlyingMotion.o: ../scene/vsTransformAttribute.h++
vsFlyingMotion.o: ../scene/vsSwitchAttribute.h++
vsFlyingMotion.o: ../scene/vsSequenceAttribute.h++
vsFlyingMotion.o: ../scene/vsLODAttribute.h++
vsFlyingMotion.o: ../scene/vsBillboardAttribute.h++ ../scene/vsGeometry.h++
vsFlyingMotion.o: ../scene/vsFogAttribute.h++
vsFlyingMotion.o: /usr/include/Performer/pr/pfFog.h
vsFlyingMotion.o: ../scene/vsMaterialAttribute.h++
vsFlyingMotion.o: /usr/include/Performer/pr/pfMaterial.h
vsFlyingMotion.o: ../scene/vsTextureAttribute.h++
vsFlyingMotion.o: /usr/include/Performer/pr/pfTexture.h
vsFlyingMotion.o: /usr/include/Performer/image.h
vsFlyingMotion.o: ../scene/vsTransparencyAttribute.h++
vsFlyingMotion.o: ../scene/vsBackfaceAttribute.h++
vsFlyingMotion.o: /usr/include/Performer/pr/pfLight.h
vsFlyingMotion.o: ../input/vsInputAxis.h++ ../input/vsInputButton.h++
vsFlyingMotion.o: ../input/vsMouse.h++ ../input/vsInputDevice.h++
vsMotionModel.o: vsMotionModel.h++ ../corelib/vsGlobals.h++
vsMotionModel.o: ../math/vsVecQuat.h++ ../math/vsMatrix.h++
vsMotionModel.o: ../math/vsVector.h++ ../math/vsQuat.h++
vsMotionModel.o: ../scene/vsComponent.h++ /usr/include/Performer/pf/pfGroup.h
vsMotionModel.o: /usr/include/Performer/pf/pfNode.h
vsMotionModel.o: /usr/include/Performer/pf/pfUpdatable.h
vsMotionModel.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsMotionModel.o: /usr/include/sys/types.h /usr/include/standards.h
vsMotionModel.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsMotionModel.o: /usr/include/ulocks.h /usr/include/limits.h
vsMotionModel.o: /usr/include/task.h /usr/include/sys/prctl.h
vsMotionModel.o: /usr/include/unistd.h /usr/include/errno.h
vsMotionModel.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsMotionModel.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsMotionModel.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsMotionModel.o: /usr/include/X11/Xutil.h
vsMotionModel.o: /usr/include/X11/extensions/XSGIvc.h
vsMotionModel.o: /usr/include/X11/extensions/XSGIvcstr.h
vsMotionModel.o: /usr/include/wctype.h /usr/include/wchar.h
vsMotionModel.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsMotionModel.o: /usr/include/time.h /usr/include/GL/gl.h
vsMotionModel.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsMotionModel.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsMotionModel.o: /usr/include/Performer/opengl.h
vsMotionModel.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsMotionModel.o: /usr/include/Performer/prstats.h
vsMotionModel.o: /usr/include/Performer/pr/pfLinMath.h
vsMotionModel.o: /usr/include/Performer/pr/pfObject.h
vsMotionModel.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsMotionModel.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsMotionModel.o: /usr/include/Performer/pr/pfStruct.h
vsMotionModel.o: /usr/include/Performer/pfstats.h
vsMotionModel.o: /usr/include/Performer/pf/pfBuffer.h
vsMotionModel.o: /usr/include/Performer/pf/pfUpdate.h
vsMotionModel.o: /usr/include/Performer/pf/pfLists.h
vsMotionModel.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsMotionModel.o: /usr/include/sys/cdefs.h
vsMotionModel.o: /usr/include/Performer/pf/pfFrameStats.h
vsMotionModel.o: /usr/include/Performer/pf/pfPipe.h
vsMotionModel.o: /usr/include/Performer/pr/pfVideoChannel.h
vsMotionModel.o: /usr/include/Performer/pr/pfList.h
vsMotionModel.o: /usr/include/Performer/pr/pfCalligraphic.h
vsMotionModel.o: /usr/include/Performer/pr/pfStats.h
vsMotionModel.o: /usr/include/Performer/pr/pfDispList.h
vsMotionModel.o: /usr/include/Performer/pr/pfGeoState.h
vsMotionModel.o: /usr/include/Performer/pr/pfState.h
vsMotionModel.o: /usr/include/Performer/pr/pfGeoMath.h
vsMotionModel.o: /usr/include/Performer/pf/pfSwitch.h
vsMotionModel.o: /usr/include/Performer/pr/pfFlux.h
vsMotionModel.o: /usr/include/Performer/pr/pfEngine.h
vsMotionModel.o: /usr/include/Performer/pf/pfSequence.h
vsMotionModel.o: /usr/include/Performer/pf/pfLOD.h
vsMotionModel.o: /usr/include/Performer/pf/pfLODState.h
vsMotionModel.o: /usr/include/Performer/pf/pfGeode.h ../corelib/vsSystem.h++
vsMotionModel.o: ../corelib/vsPipe.h++ ../corelib/vsScreen.h++
vsMotionModel.o: ../corelib/vsWindow.h++
vsMotionModel.o: /usr/include/Performer/pf/pfPipeWindow.h
vsMotionModel.o: /usr/include/Performer/pr/pfWindow.h ../corelib/vsPane.h++
vsMotionModel.o: /usr/include/Performer/pf/pfChannel.h
vsMotionModel.o: /usr/include/Performer/pf/pfPipeVideoChannel.h
vsMotionModel.o: /usr/include/Performer/pf/pfEarthSky.h
vsMotionModel.o: /usr/include/Performer/pf/pfScene.h
vsMotionModel.o: /usr/include/Performer/pr/pfGeoSet.h
vsMotionModel.o: /usr/include/Performer/pr/pfCycleBuffer.h
vsMotionModel.o: ../corelib/vsView.h++ ../scene/vsViewpointAttribute.h++
vsMotionModel.o: /usr/include/Performer/pf/pfSCS.h ../scene/vsNode.h++
vsMotionModel.o: ../scene/vsAttributeList.h++ ../scene/vsAttribute.h++
vsMotionModel.o: /usr/include/stdlib.h ../corelib/vsDatabaseLoader.h++
vsMotionModel.o: /usr/include/Performer/pf/pfBillboard.h
vsMotionModel.o: /usr/include/Performer/pf/pfCuller.h /usr/include/alloca.h
vsMotionModel.o: /usr/include/Performer/pf/pfTraverser.h
vsMotionModel.o: /usr/include/Performer/pr/pfSprite.h
vsMotionModel.o: /usr/include/Performer/pf/pfDCS.h
vsMotionModel.o: /usr/include/Performer/pfdu.h
vsMotionModel.o: /usr/include/Performer/pfutil.h /usr/include/dlfcn.h
vsMotionModel.o: /usr/include/Performer/objfnt.h
vsMotionModel.o: /usr/include/Performer/pfdb/pfflt.h
vsMotionModel.o: ../corelib/vsObjectMap.h++ ../scene/vsTransformAttribute.h++
vsMotionModel.o: ../scene/vsSwitchAttribute.h++
vsMotionModel.o: ../scene/vsSequenceAttribute.h++ ../scene/vsLODAttribute.h++
vsMotionModel.o: ../scene/vsBillboardAttribute.h++ ../scene/vsGeometry.h++
vsMotionModel.o: ../scene/vsFogAttribute.h++
vsMotionModel.o: /usr/include/Performer/pr/pfFog.h
vsMotionModel.o: ../scene/vsMaterialAttribute.h++
vsMotionModel.o: /usr/include/Performer/pr/pfMaterial.h
vsMotionModel.o: ../scene/vsTextureAttribute.h++
vsMotionModel.o: /usr/include/Performer/pr/pfTexture.h
vsMotionModel.o: /usr/include/Performer/image.h
vsMotionModel.o: ../scene/vsTransparencyAttribute.h++
vsMotionModel.o: ../scene/vsBackfaceAttribute.h++
vsMotionModel.o: /usr/include/Performer/pr/pfLight.h ../input/vsInputAxis.h++
vsMotionModel.o: ../input/vsInputButton.h++ /usr/include/sys/time.h
vsTrackballMotion.o: vsTrackballMotion.h++ vsMotionModel.h++
vsTrackballMotion.o: ../corelib/vsGlobals.h++ ../math/vsVecQuat.h++
vsTrackballMotion.o: ../math/vsMatrix.h++ ../math/vsVector.h++
vsTrackballMotion.o: ../math/vsQuat.h++ ../scene/vsComponent.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfGroup.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfNode.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsTrackballMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsTrackballMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsTrackballMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsTrackballMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsTrackballMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsTrackballMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsTrackballMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsTrackballMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsTrackballMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsTrackballMotion.o: /usr/include/X11/Xutil.h
vsTrackballMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsTrackballMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsTrackballMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsTrackballMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsTrackballMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsTrackballMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsTrackballMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsTrackballMotion.o: /usr/include/Performer/opengl.h
vsTrackballMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsTrackballMotion.o: /usr/include/Performer/prstats.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfObject.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfMemory.h
vsTrackballMotion.o: /usr/include/string.h /usr/include/bstring.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfType.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfStruct.h
vsTrackballMotion.o: /usr/include/Performer/pfstats.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfLists.h
vsTrackballMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsTrackballMotion.o: /usr/include/sys/cdefs.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfPipe.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfList.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfStats.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfDispList.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfState.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfSwitch.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfFlux.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfEngine.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfSequence.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfLOD.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfLODState.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfGeode.h
vsTrackballMotion.o: ../corelib/vsSystem.h++ ../corelib/vsPipe.h++
vsTrackballMotion.o: ../corelib/vsScreen.h++ ../corelib/vsWindow.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfPipeWindow.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfWindow.h
vsTrackballMotion.o: ../corelib/vsPane.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfChannel.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfPipeVideoChannel.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfEarthSky.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfScene.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfGeoSet.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfCycleBuffer.h
vsTrackballMotion.o: ../corelib/vsView.h++ ../scene/vsViewpointAttribute.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfSCS.h ../scene/vsNode.h++
vsTrackballMotion.o: ../scene/vsAttributeList.h++ ../scene/vsAttribute.h++
vsTrackballMotion.o: /usr/include/stdlib.h ../corelib/vsDatabaseLoader.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfBillboard.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfCuller.h
vsTrackballMotion.o: /usr/include/alloca.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfTraverser.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfSprite.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfDCS.h
vsTrackballMotion.o: /usr/include/Performer/pfdu.h
vsTrackballMotion.o: /usr/include/Performer/pfutil.h /usr/include/dlfcn.h
vsTrackballMotion.o: /usr/include/Performer/objfnt.h
vsTrackballMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsTrackballMotion.o: ../corelib/vsObjectMap.h++
vsTrackballMotion.o: ../scene/vsTransformAttribute.h++
vsTrackballMotion.o: ../scene/vsSwitchAttribute.h++
vsTrackballMotion.o: ../scene/vsSequenceAttribute.h++
vsTrackballMotion.o: ../scene/vsLODAttribute.h++
vsTrackballMotion.o: ../scene/vsBillboardAttribute.h++
vsTrackballMotion.o: ../scene/vsGeometry.h++ ../scene/vsFogAttribute.h++
vsTrackballMotion.o: /usr/include/Performer/pr/pfFog.h
vsTrackballMotion.o: ../scene/vsMaterialAttribute.h++
vsTrackballMotion.o: /usr/include/Performer/pr/pfMaterial.h
vsTrackballMotion.o: ../scene/vsTextureAttribute.h++
vsTrackballMotion.o: /usr/include/Performer/pr/pfTexture.h
vsTrackballMotion.o: /usr/include/Performer/image.h
vsTrackballMotion.o: ../scene/vsTransparencyAttribute.h++
vsTrackballMotion.o: ../scene/vsBackfaceAttribute.h++
vsTrackballMotion.o: /usr/include/Performer/pr/pfLight.h
vsTrackballMotion.o: ../input/vsInputAxis.h++ ../input/vsInputButton.h++
vsTrackballMotion.o: ../input/vsMouse.h++ ../input/vsInputDevice.h++
vsTrackedMotion.o: vsTrackedMotion.h++ vsMotionModel.h++
vsTrackedMotion.o: ../corelib/vsGlobals.h++ ../math/vsVecQuat.h++
vsTrackedMotion.o: ../math/vsMatrix.h++ ../math/vsVector.h++
vsTrackedMotion.o: ../math/vsQuat.h++ ../scene/vsComponent.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfGroup.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfNode.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsTrackedMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsTrackedMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsTrackedMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsTrackedMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsTrackedMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsTrackedMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsTrackedMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsTrackedMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsTrackedMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsTrackedMotion.o: /usr/include/X11/Xutil.h
vsTrackedMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsTrackedMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsTrackedMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsTrackedMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsTrackedMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsTrackedMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsTrackedMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsTrackedMotion.o: /usr/include/Performer/opengl.h
vsTrackedMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsTrackedMotion.o: /usr/include/Performer/prstats.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfObject.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsTrackedMotion.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfStruct.h
vsTrackedMotion.o: /usr/include/Performer/pfstats.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfLists.h
vsTrackedMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsTrackedMotion.o: /usr/include/sys/cdefs.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfPipe.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfList.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfStats.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfDispList.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfState.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfSwitch.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfFlux.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfEngine.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfSequence.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfLOD.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfLODState.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfGeode.h
vsTrackedMotion.o: ../corelib/vsSystem.h++ ../corelib/vsPipe.h++
vsTrackedMotion.o: ../corelib/vsScreen.h++ ../corelib/vsWindow.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfPipeWindow.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfWindow.h ../corelib/vsPane.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfChannel.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfPipeVideoChannel.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfEarthSky.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfScene.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfGeoSet.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfCycleBuffer.h
vsTrackedMotion.o: ../corelib/vsView.h++ ../scene/vsViewpointAttribute.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfSCS.h ../scene/vsNode.h++
vsTrackedMotion.o: ../scene/vsAttributeList.h++ ../scene/vsAttribute.h++
vsTrackedMotion.o: /usr/include/stdlib.h ../corelib/vsDatabaseLoader.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfBillboard.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfCuller.h /usr/include/alloca.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfTraverser.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfSprite.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfDCS.h
vsTrackedMotion.o: /usr/include/Performer/pfdu.h
vsTrackedMotion.o: /usr/include/Performer/pfutil.h /usr/include/dlfcn.h
vsTrackedMotion.o: /usr/include/Performer/objfnt.h
vsTrackedMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsTrackedMotion.o: ../corelib/vsObjectMap.h++
vsTrackedMotion.o: ../scene/vsTransformAttribute.h++
vsTrackedMotion.o: ../scene/vsSwitchAttribute.h++
vsTrackedMotion.o: ../scene/vsSequenceAttribute.h++
vsTrackedMotion.o: ../scene/vsLODAttribute.h++
vsTrackedMotion.o: ../scene/vsBillboardAttribute.h++ ../scene/vsGeometry.h++
vsTrackedMotion.o: ../scene/vsFogAttribute.h++
vsTrackedMotion.o: /usr/include/Performer/pr/pfFog.h
vsTrackedMotion.o: ../scene/vsMaterialAttribute.h++
vsTrackedMotion.o: /usr/include/Performer/pr/pfMaterial.h
vsTrackedMotion.o: ../scene/vsTextureAttribute.h++
vsTrackedMotion.o: /usr/include/Performer/pr/pfTexture.h
vsTrackedMotion.o: /usr/include/Performer/image.h
vsTrackedMotion.o: ../scene/vsTransparencyAttribute.h++
vsTrackedMotion.o: ../scene/vsBackfaceAttribute.h++
vsTrackedMotion.o: /usr/include/Performer/pr/pfLight.h
vsTrackedMotion.o: ../input/vsInputAxis.h++ ../input/vsInputButton.h++
vsTrackedMotion.o: ../input/vsMotionTracker.h++ ../input/vs6DInputDevice.h++
vsTrackedMotion.o: ../input/vsInputDevice.h++
