#!/bin/make
#======================================================================
#		makefile
#======================================================================


#----------------------------------------------------------------------
#   Notes:
#
#	To add a new file to the system, simply list its source and
#	object files immediately below, then run 'make dep' --- this 
#	will make the new dependencies
#

#----------------------------------------------------------------------
#                       Name of the library
#----------------------------------------------------------------------
LIBNAME = libvsMotion.a

#----------------------------------------------------------------------
#			All Source and Object files
#----------------------------------------------------------------------
SRCS = \
       vs3TrackerArm.c++ \
       vsDrivingMotion.c++ \
       vsFlyingMotion.c++ \
       vsHeadMotion.c++ \
       vsKinematics.c++ \
       vsMotionModel.c++ \
       vsTrackballMotion.c++ \
       vsTrackedMotion.c++ \
       vsWalkInPlace.c++

OBJS = \
       vs3TrackerArm.o \
       vsDrivingMotion.o \
       vsFlyingMotion.o \
       vsHeadMotion.o \
       vsKinematics.o \
       vsMotionModel.o \
       vsTrackballMotion.o \
       vsTrackedMotion.o \
       vsWalkInPlace.o

#----------------------------------------------------------------------
#			Misc. settings
#----------------------------------------------------------------------
OS = IRIX64

#----------------------------------------------------------------------
#			Compiler settings
#----------------------------------------------------------------------
CC = cc
CXX = CC
AR = ar
CFLAGS = -g -D$(OS) -n32 -mips3 -DSGI -xansi $(INCS)
CXXFLAGS = -g -D$(OS) -xansi -n32 -DSGI -mips3 $(INCS)
ARFLAGS = -rulc

#----------------------------------------------------------------------
#			Include file directories
#----------------------------------------------------------------------
INCS = \
       -I../corelib \
       -I../scene \
       -I../math \
       -I../input

#----------------------------------------------------------------------
#			Default target
#----------------------------------------------------------------------
all: $(LIBNAME)

#----------------------------------------------------------------------
#			Library archive rules
#----------------------------------------------------------------------
$(LIBNAME): $(OBJS)
	ar $(ARFLAGS) $(LIBNAME) $(OBJS)

#----------------------------------------------------------------------
#			Inference Rules
#----------------------------------------------------------------------
.c++.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

.c.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f core
	rm -f $(LIBNAME)
	rm -f makefile.*.bak

#----------------------------------------------------------------------
#			This is the dependency update rule
#----------------------------------------------------------------------
dep: depend
depend:
	makedepend -f makefile.IRIX64 -- $(CFLAGS) $(INCS) -- $(SRCS)
#----------------------------------------------------------------------
# Our automatically generated dependencies follow...
# Please don't mess below this line
# DO NOT DELETE

vs3TrackerArm.o: vs3TrackerArm.h++ vsMotionModel.h++ vsKinematics.h++
vs3TrackerArm.o: ../scene/vsComponent.h++ /usr/include/Performer/pf/pfGroup.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfNode.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfUpdatable.h
vs3TrackerArm.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vs3TrackerArm.o: /usr/include/sys/types.h /usr/include/standards.h
vs3TrackerArm.o: /usr/include/sgidefs.h /usr/include/stdio.h
vs3TrackerArm.o: /usr/include/ulocks.h /usr/include/limits.h
vs3TrackerArm.o: /usr/include/task.h /usr/include/sys/prctl.h
vs3TrackerArm.o: /usr/include/unistd.h /usr/include/errno.h
vs3TrackerArm.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vs3TrackerArm.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vs3TrackerArm.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vs3TrackerArm.o: /usr/include/X11/Xutil.h
vs3TrackerArm.o: /usr/include/X11/extensions/XSGIvc.h
vs3TrackerArm.o: /usr/include/X11/extensions/XSGIvcstr.h
vs3TrackerArm.o: /usr/include/wctype.h /usr/include/wchar.h
vs3TrackerArm.o: /usr/include/locale_attr.h /usr/include/ctype.h
vs3TrackerArm.o: /usr/include/time.h /usr/include/GL/gl.h
vs3TrackerArm.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vs3TrackerArm.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vs3TrackerArm.o: /usr/include/Performer/opengl.h
vs3TrackerArm.o: /usr/include/Performer/prmath.h /usr/include/math.h
vs3TrackerArm.o: /usr/include/Performer/prstats.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfLinMath.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfObject.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vs3TrackerArm.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfStruct.h
vs3TrackerArm.o: /usr/include/Performer/pfstats.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfBuffer.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfUpdate.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfLists.h
vs3TrackerArm.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vs3TrackerArm.o: /usr/include/sys/cdefs.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfFrameStats.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfPipe.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfVideoChannel.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfList.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfCalligraphic.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfStats.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfDispList.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfGeoState.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfState.h
vs3TrackerArm.o: /usr/include/Performer/pr/pfGeoMath.h
vs3TrackerArm.o: ../corelib/vsGrowableArray.h++ ../math/vsVector.h++
vs3TrackerArm.o: ../corelib/vsGlobals.h++ ../scene/vsAttribute.h++
vs3TrackerArm.o: /usr/include/stdlib.h ../scene/vsNode.h++
vs3TrackerArm.o: ../scene/vsAttributeList.h++ ../corelib/vsDatabaseLoader.h++
vs3TrackerArm.o: /usr/include/Performer/pfdb/pfflt.h
vs3TrackerArm.o: ../scene/vsTransformAttribute.h++
vs3TrackerArm.o: /usr/include/Performer/pf/pfDCS.h
vs3TrackerArm.o: /usr/include/Performer/pf/pfSCS.h ../math/vsMatrix.h++
vs3TrackerArm.o: ../math/vsQuat.h++ ../input/vsMotionTracker.h++
vs3TrackerArm.o: ../input/vs6DInputDevice.h++ ../input/vsInputDevice.h++
vs3TrackerArm.o: ../input/vsInputAxis.h++ ../input/vsInputButton.h++
vsDrivingMotion.o: vsDrivingMotion.h++ vsMotionModel.h++ vsKinematics.h++
vsDrivingMotion.o: ../scene/vsComponent.h++
vsDrivingMotion.o: /usr/include/Performer/pf/pfGroup.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfNode.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsDrivingMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsDrivingMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsDrivingMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsDrivingMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsDrivingMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsDrivingMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsDrivingMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsDrivingMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsDrivingMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsDrivingMotion.o: /usr/include/X11/Xutil.h
vsDrivingMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsDrivingMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsDrivingMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsDrivingMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsDrivingMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsDrivingMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsDrivingMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsDrivingMotion.o: /usr/include/Performer/opengl.h
vsDrivingMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsDrivingMotion.o: /usr/include/Performer/prstats.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfObject.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsDrivingMotion.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfStruct.h
vsDrivingMotion.o: /usr/include/Performer/pfstats.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfLists.h
vsDrivingMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsDrivingMotion.o: /usr/include/sys/cdefs.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfPipe.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfList.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfStats.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfDispList.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfState.h
vsDrivingMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsDrivingMotion.o: ../corelib/vsGrowableArray.h++ ../math/vsVector.h++
vsDrivingMotion.o: ../corelib/vsGlobals.h++ ../scene/vsAttribute.h++
vsDrivingMotion.o: /usr/include/stdlib.h ../scene/vsNode.h++
vsDrivingMotion.o: ../scene/vsAttributeList.h++
vsDrivingMotion.o: ../corelib/vsDatabaseLoader.h++
vsDrivingMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsDrivingMotion.o: ../scene/vsTransformAttribute.h++
vsDrivingMotion.o: /usr/include/Performer/pf/pfDCS.h
vsDrivingMotion.o: /usr/include/Performer/pf/pfSCS.h ../math/vsMatrix.h++
vsDrivingMotion.o: ../math/vsQuat.h++ ../input/vsMouse.h++
vsDrivingMotion.o: ../input/vsInputDevice.h++ ../input/vsInputAxis.h++
vsDrivingMotion.o: ../input/vsInputButton.h++
vsFlyingMotion.o: vsFlyingMotion.h++ vsMotionModel.h++ ../input/vsMouse.h++
vsFlyingMotion.o: ../input/vsInputDevice.h++ ../corelib/vsGlobals.h++
vsFlyingMotion.o: ../input/vsInputAxis.h++ ../input/vsInputButton.h++
vsFlyingMotion.o: vsKinematics.h++ ../scene/vsComponent.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfGroup.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfNode.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsFlyingMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsFlyingMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsFlyingMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsFlyingMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsFlyingMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsFlyingMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsFlyingMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsFlyingMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsFlyingMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsFlyingMotion.o: /usr/include/X11/Xutil.h
vsFlyingMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsFlyingMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsFlyingMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsFlyingMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsFlyingMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsFlyingMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsFlyingMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsFlyingMotion.o: /usr/include/Performer/opengl.h
vsFlyingMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsFlyingMotion.o: /usr/include/Performer/prstats.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfObject.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsFlyingMotion.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfStruct.h
vsFlyingMotion.o: /usr/include/Performer/pfstats.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfLists.h
vsFlyingMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsFlyingMotion.o: /usr/include/sys/cdefs.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfPipe.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfList.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfStats.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfDispList.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfState.h
vsFlyingMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsFlyingMotion.o: ../corelib/vsGrowableArray.h++ ../math/vsVector.h++
vsFlyingMotion.o: ../scene/vsAttribute.h++ /usr/include/stdlib.h
vsFlyingMotion.o: ../scene/vsNode.h++ ../scene/vsAttributeList.h++
vsFlyingMotion.o: ../corelib/vsDatabaseLoader.h++
vsFlyingMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsFlyingMotion.o: ../scene/vsTransformAttribute.h++
vsFlyingMotion.o: /usr/include/Performer/pf/pfDCS.h
vsFlyingMotion.o: /usr/include/Performer/pf/pfSCS.h ../math/vsMatrix.h++
vsFlyingMotion.o: ../math/vsQuat.h++
vsKinematics.o: vsKinematics.h++ ../scene/vsComponent.h++
vsKinematics.o: /usr/include/Performer/pf/pfGroup.h
vsKinematics.o: /usr/include/Performer/pf/pfNode.h
vsKinematics.o: /usr/include/Performer/pf/pfUpdatable.h
vsKinematics.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsKinematics.o: /usr/include/sys/types.h /usr/include/standards.h
vsKinematics.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsKinematics.o: /usr/include/ulocks.h /usr/include/limits.h
vsKinematics.o: /usr/include/task.h /usr/include/sys/prctl.h
vsKinematics.o: /usr/include/unistd.h /usr/include/errno.h
vsKinematics.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsKinematics.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsKinematics.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsKinematics.o: /usr/include/X11/Xutil.h /usr/include/X11/extensions/XSGIvc.h
vsKinematics.o: /usr/include/X11/extensions/XSGIvcstr.h /usr/include/wctype.h
vsKinematics.o: /usr/include/wchar.h /usr/include/locale_attr.h
vsKinematics.o: /usr/include/ctype.h /usr/include/time.h /usr/include/GL/gl.h
vsKinematics.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsKinematics.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsKinematics.o: /usr/include/Performer/opengl.h
vsKinematics.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsKinematics.o: /usr/include/Performer/prstats.h
vsKinematics.o: /usr/include/Performer/pr/pfLinMath.h
vsKinematics.o: /usr/include/Performer/pr/pfObject.h
vsKinematics.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsKinematics.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsKinematics.o: /usr/include/Performer/pr/pfStruct.h
vsKinematics.o: /usr/include/Performer/pfstats.h
vsKinematics.o: /usr/include/Performer/pf/pfBuffer.h
vsKinematics.o: /usr/include/Performer/pf/pfUpdate.h
vsKinematics.o: /usr/include/Performer/pf/pfLists.h /usr/include/sys/stream.h
vsKinematics.o: /usr/include/sys/strmdep.h /usr/include/sys/cdefs.h
vsKinematics.o: /usr/include/Performer/pf/pfFrameStats.h
vsKinematics.o: /usr/include/Performer/pf/pfPipe.h
vsKinematics.o: /usr/include/Performer/pr/pfVideoChannel.h
vsKinematics.o: /usr/include/Performer/pr/pfList.h
vsKinematics.o: /usr/include/Performer/pr/pfCalligraphic.h
vsKinematics.o: /usr/include/Performer/pr/pfStats.h
vsKinematics.o: /usr/include/Performer/pr/pfDispList.h
vsKinematics.o: /usr/include/Performer/pr/pfGeoState.h
vsKinematics.o: /usr/include/Performer/pr/pfState.h
vsKinematics.o: /usr/include/Performer/pr/pfGeoMath.h
vsKinematics.o: ../corelib/vsGrowableArray.h++ ../math/vsVector.h++
vsKinematics.o: ../corelib/vsGlobals.h++ ../scene/vsAttribute.h++
vsKinematics.o: /usr/include/stdlib.h ../scene/vsNode.h++
vsKinematics.o: ../scene/vsAttributeList.h++ ../corelib/vsDatabaseLoader.h++
vsKinematics.o: /usr/include/Performer/pfdb/pfflt.h
vsKinematics.o: ../scene/vsTransformAttribute.h++
vsKinematics.o: /usr/include/Performer/pf/pfDCS.h
vsKinematics.o: /usr/include/Performer/pf/pfSCS.h ../math/vsMatrix.h++
vsKinematics.o: ../math/vsQuat.h++ /usr/include/sys/time.h
vsMotionModel.o: vsMotionModel.h++ /usr/include/sys/time.h
vsMotionModel.o: /usr/include/standards.h /usr/include/sgidefs.h
vsTrackballMotion.o: vsTrackballMotion.h++ vsMotionModel.h++
vsTrackballMotion.o: ../input/vsMouse.h++ ../input/vsInputDevice.h++
vsTrackballMotion.o: ../corelib/vsGlobals.h++ ../input/vsInputAxis.h++
vsTrackballMotion.o: ../input/vsInputButton.h++ vsKinematics.h++
vsTrackballMotion.o: ../scene/vsComponent.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfGroup.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfNode.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsTrackballMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsTrackballMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsTrackballMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsTrackballMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsTrackballMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsTrackballMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsTrackballMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsTrackballMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsTrackballMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsTrackballMotion.o: /usr/include/X11/Xutil.h
vsTrackballMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsTrackballMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsTrackballMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsTrackballMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsTrackballMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsTrackballMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsTrackballMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsTrackballMotion.o: /usr/include/Performer/opengl.h
vsTrackballMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsTrackballMotion.o: /usr/include/Performer/prstats.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfObject.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfMemory.h
vsTrackballMotion.o: /usr/include/string.h /usr/include/bstring.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfType.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfStruct.h
vsTrackballMotion.o: /usr/include/Performer/pfstats.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfLists.h
vsTrackballMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsTrackballMotion.o: /usr/include/sys/cdefs.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfPipe.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfList.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfStats.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfDispList.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfState.h
vsTrackballMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsTrackballMotion.o: ../corelib/vsGrowableArray.h++ ../math/vsVector.h++
vsTrackballMotion.o: ../scene/vsAttribute.h++ /usr/include/stdlib.h
vsTrackballMotion.o: ../scene/vsNode.h++ ../scene/vsAttributeList.h++
vsTrackballMotion.o: ../corelib/vsDatabaseLoader.h++
vsTrackballMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsTrackballMotion.o: ../scene/vsTransformAttribute.h++
vsTrackballMotion.o: /usr/include/Performer/pf/pfDCS.h
vsTrackballMotion.o: /usr/include/Performer/pf/pfSCS.h ../math/vsMatrix.h++
vsTrackballMotion.o: ../math/vsQuat.h++
vsTrackedMotion.o: vsTrackedMotion.h++ vsMotionModel.h++
vsTrackedMotion.o: ../input/vsMotionTracker.h++ ../input/vs6DInputDevice.h++
vsTrackedMotion.o: ../math/vsVector.h++ ../corelib/vsGlobals.h++
vsTrackedMotion.o: ../math/vsMatrix.h++ ../math/vsQuat.h++
vsTrackedMotion.o: ../input/vsInputDevice.h++ ../input/vsInputAxis.h++
vsTrackedMotion.o: ../input/vsInputButton.h++ vsKinematics.h++
vsTrackedMotion.o: ../scene/vsComponent.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfGroup.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfNode.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfUpdatable.h
vsTrackedMotion.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsTrackedMotion.o: /usr/include/sys/types.h /usr/include/standards.h
vsTrackedMotion.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsTrackedMotion.o: /usr/include/ulocks.h /usr/include/limits.h
vsTrackedMotion.o: /usr/include/task.h /usr/include/sys/prctl.h
vsTrackedMotion.o: /usr/include/unistd.h /usr/include/errno.h
vsTrackedMotion.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsTrackedMotion.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsTrackedMotion.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsTrackedMotion.o: /usr/include/X11/Xutil.h
vsTrackedMotion.o: /usr/include/X11/extensions/XSGIvc.h
vsTrackedMotion.o: /usr/include/X11/extensions/XSGIvcstr.h
vsTrackedMotion.o: /usr/include/wctype.h /usr/include/wchar.h
vsTrackedMotion.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsTrackedMotion.o: /usr/include/time.h /usr/include/GL/gl.h
vsTrackedMotion.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsTrackedMotion.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsTrackedMotion.o: /usr/include/Performer/opengl.h
vsTrackedMotion.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsTrackedMotion.o: /usr/include/Performer/prstats.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfLinMath.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfObject.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsTrackedMotion.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfStruct.h
vsTrackedMotion.o: /usr/include/Performer/pfstats.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfBuffer.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfUpdate.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfLists.h
vsTrackedMotion.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsTrackedMotion.o: /usr/include/sys/cdefs.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfFrameStats.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfPipe.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfVideoChannel.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfList.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfCalligraphic.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfStats.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfDispList.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfGeoState.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfState.h
vsTrackedMotion.o: /usr/include/Performer/pr/pfGeoMath.h
vsTrackedMotion.o: ../corelib/vsGrowableArray.h++ ../scene/vsAttribute.h++
vsTrackedMotion.o: /usr/include/stdlib.h ../scene/vsNode.h++
vsTrackedMotion.o: ../scene/vsAttributeList.h++
vsTrackedMotion.o: ../corelib/vsDatabaseLoader.h++
vsTrackedMotion.o: /usr/include/Performer/pfdb/pfflt.h
vsTrackedMotion.o: ../scene/vsTransformAttribute.h++
vsTrackedMotion.o: /usr/include/Performer/pf/pfDCS.h
vsTrackedMotion.o: /usr/include/Performer/pf/pfSCS.h
vsWalkInPlace.o: vsWalkInPlace.h++ vsMotionModel.h++
vsWalkInPlace.o: ../input/vsMotionTracker.h++ ../input/vs6DInputDevice.h++
vsWalkInPlace.o: ../math/vsVector.h++ ../corelib/vsGlobals.h++
vsWalkInPlace.o: ../math/vsMatrix.h++ ../math/vsQuat.h++
vsWalkInPlace.o: ../input/vsInputDevice.h++ ../input/vsInputAxis.h++
vsWalkInPlace.o: ../input/vsInputButton.h++ vsKinematics.h++
vsWalkInPlace.o: ../scene/vsComponent.h++ /usr/include/Performer/pf/pfGroup.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfNode.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfUpdatable.h
vsWalkInPlace.o: /usr/include/Performer/pf.h /usr/include/Performer/pr.h
vsWalkInPlace.o: /usr/include/sys/types.h /usr/include/standards.h
vsWalkInPlace.o: /usr/include/sgidefs.h /usr/include/stdio.h
vsWalkInPlace.o: /usr/include/ulocks.h /usr/include/limits.h
vsWalkInPlace.o: /usr/include/task.h /usr/include/sys/prctl.h
vsWalkInPlace.o: /usr/include/unistd.h /usr/include/errno.h
vsWalkInPlace.o: /usr/include/sys/errno.h /usr/include/X11/X.h
vsWalkInPlace.o: /usr/include/X11/Xlib.h /usr/include/X11/Xfuncproto.h
vsWalkInPlace.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
vsWalkInPlace.o: /usr/include/X11/Xutil.h
vsWalkInPlace.o: /usr/include/X11/extensions/XSGIvc.h
vsWalkInPlace.o: /usr/include/X11/extensions/XSGIvcstr.h
vsWalkInPlace.o: /usr/include/wctype.h /usr/include/wchar.h
vsWalkInPlace.o: /usr/include/locale_attr.h /usr/include/ctype.h
vsWalkInPlace.o: /usr/include/time.h /usr/include/GL/gl.h
vsWalkInPlace.o: /usr/include/GL/glx.h /usr/include/X11/Xmd.h
vsWalkInPlace.o: /usr/include/GL/glxtokens.h /usr/include/GL/glu.h
vsWalkInPlace.o: /usr/include/Performer/opengl.h
vsWalkInPlace.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsWalkInPlace.o: /usr/include/Performer/prstats.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfLinMath.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfObject.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfMemory.h /usr/include/string.h
vsWalkInPlace.o: /usr/include/bstring.h /usr/include/Performer/pr/pfType.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfStruct.h
vsWalkInPlace.o: /usr/include/Performer/pfstats.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfBuffer.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfUpdate.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfLists.h
vsWalkInPlace.o: /usr/include/sys/stream.h /usr/include/sys/strmdep.h
vsWalkInPlace.o: /usr/include/sys/cdefs.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfFrameStats.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfPipe.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfVideoChannel.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfList.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfCalligraphic.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfStats.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfDispList.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfGeoState.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfState.h
vsWalkInPlace.o: /usr/include/Performer/pr/pfGeoMath.h
vsWalkInPlace.o: ../corelib/vsGrowableArray.h++ ../scene/vsAttribute.h++
vsWalkInPlace.o: /usr/include/stdlib.h ../scene/vsNode.h++
vsWalkInPlace.o: ../scene/vsAttributeList.h++ ../corelib/vsDatabaseLoader.h++
vsWalkInPlace.o: /usr/include/Performer/pfdb/pfflt.h
vsWalkInPlace.o: ../scene/vsTransformAttribute.h++
vsWalkInPlace.o: /usr/include/Performer/pf/pfDCS.h
vsWalkInPlace.o: /usr/include/Performer/pf/pfSCS.h
