#!/bin/make
#======================================================================
#		makefile
#======================================================================


#----------------------------------------------------------------------
#   Notes:
#
#	To add a new file to the system, simply list its source and
#	object files immediately below, then run 'make dep' --- this 
#	will make the new dependencies
#

#----------------------------------------------------------------------
#                       Name of the library
#----------------------------------------------------------------------
LIBNAME = libvsSound.a

#----------------------------------------------------------------------
#			All Source and Object files
#----------------------------------------------------------------------
SRCS = \
       vsSoundBuffer.c++ \
       vsSoundListenerAttribute.c++ \
       vsSoundPipe.c++ \
       vsSoundSample.c++ \
       vsSoundSourceAttribute.c++

OBJS = \
       vsSoundBuffer.o \
       vsSoundListenerAttribute.o \
       vsSoundPipe.o \
       vsSoundSample.o \
       vsSoundSourceAttribute.o

#----------------------------------------------------------------------
#			Misc. settings
#----------------------------------------------------------------------
OS = LINUX

#----------------------------------------------------------------------
#			Compiler settings
#----------------------------------------------------------------------
CC = gcc
CXX = g++ 
AR = ar
CFLAGS = -g -O -D_XOPEN_SOURCE -D_BSD_SOURCE -D_MISC_SOURCE -D$(OS) -D__linux__ -ansi $(INCS)
CXXFLAGS = -g -O -D_XOPEN_SOURCE -D_BSD_SOURCE -D_MISC_SOURCE -D$(OS) -D__linux__ -ansi $(INCS)
ARFLAGS = -ruc

#----------------------------------------------------------------------
#			Include file directories
#----------------------------------------------------------------------
INCS = \
       -I.. \
       -I../scene \
       -I../math \
       -I../input \
       -I../corelib \
       -I/usr/include/g++-2 \
       -I/usr/X11R6/include \
       -I/ist/projects/vr2/usr/jdaly/openal/include \
       -I/ist/projects/vr2/usr/jdaly/openal/linux/include

#----------------------------------------------------------------------
#			Linking Libraries - directories and libs
#----------------------------------------------------------------------
LDIRS = \
      -nostdlib \
      -L/usr/lib32/mips3 \
      -L/usr/lib32/internal \
      -L/usr/lib32/libpfdb \
      -L/usr/lib32

LLIBS = -ignore_unresolved \
	-lC \
	-lc \
	-lm

LIBS = $(LDIRS) $(LLIBS)

#----------------------------------------------------------------------
#			Default target
#----------------------------------------------------------------------
all: $(LIBNAME)

#----------------------------------------------------------------------
#			Library archive rules
#----------------------------------------------------------------------
$(LIBNAME): $(OBJS)
	ar $(ARFLAGS) $(LIBNAME) $(OBJS)

#----------------------------------------------------------------------
#			Inference Rules
#----------------------------------------------------------------------
.SUFFIXES: .c .c++ .o .h .h++

.c++.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

.c.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f core
	rm -f $(LIBNAME)
	rm -f makefile.*.bak

#----------------------------------------------------------------------
#			This is the dependency update rule
#----------------------------------------------------------------------
dep: depend
depend:
	makedepend -f makefile.Linux -- $(CFLAGS) $(INCS) -- $(SRCS)
#----------------------------------------------------------------------
# Our automatically generated dependencies follow...
# Please don't mess below this line
# DO NOT DELETE

vsSoundBuffer.o: vsSoundBuffer.h++
vsSoundBuffer.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/al.h
vsSoundBuffer.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundListenerAttribute.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/al.h
vsSoundListenerAttribute.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundListenerAttribute.o: /usr/include/sys/time.h /usr/include/features.h
vsSoundListenerAttribute.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
vsSoundListenerAttribute.o: /usr/include/time.h
vsSoundListenerAttribute.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
vsSoundListenerAttribute.o: /usr/include/bits/time.h
vsSoundListenerAttribute.o: /usr/include/bits/types.h
vsSoundListenerAttribute.o: /usr/include/sys/select.h
vsSoundListenerAttribute.o: /usr/include/bits/select.h
vsSoundListenerAttribute.o: /usr/include/bits/sigset.h /usr/include/stdio.h
vsSoundListenerAttribute.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
vsSoundListenerAttribute.o: /usr/include/libio.h /usr/include/_G_config.h
vsSoundListenerAttribute.o: /usr/include/bits/stdio_lim.h
vsSoundListenerAttribute.o: /usr/include/getopt.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfSCS.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfGroup.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfNode.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfUpdatable.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr.h
vsSoundListenerAttribute.o: /usr/include/sys/types.h /usr/include/endian.h
vsSoundListenerAttribute.o: /usr/include/bits/endian.h
vsSoundListenerAttribute.o: /usr/include/sys/sysmacros.h
vsSoundListenerAttribute.o: /usr/include/unistd.h
vsSoundListenerAttribute.o: /usr/include/bits/posix_opt.h
vsSoundListenerAttribute.o: /usr/include/bits/confname.h /usr/include/errno.h
vsSoundListenerAttribute.o: /usr/include/bits/errno.h
vsSoundListenerAttribute.o: /usr/include/linux/errno.h
vsSoundListenerAttribute.o: /usr/include/asm/errno.h
vsSoundListenerAttribute.o: /usr/X11R6/include/X11/X.h
vsSoundListenerAttribute.o: /usr/X11R6/include/X11/Xlib.h
vsSoundListenerAttribute.o: /usr/X11R6/include/X11/Xfuncproto.h
vsSoundListenerAttribute.o: /usr/X11R6/include/X11/Xosdefs.h
vsSoundListenerAttribute.o: /usr/X11R6/include/X11/Xutil.h
vsSoundListenerAttribute.o: /usr/X11R6/include/GL/gl.h
vsSoundListenerAttribute.o: /usr/X11R6/include/GL/glx.h
vsSoundListenerAttribute.o: /usr/X11R6/include/GL/glu.h
vsSoundListenerAttribute.o: /usr/include/Performer/opengl.h
vsSoundListenerAttribute.o: /usr/include/Performer/linuxstubs.h
vsSoundListenerAttribute.o: /usr/include/Performer/image.h
vsSoundListenerAttribute.o: /usr/include/stdlib.h /usr/include/alloca.h
vsSoundListenerAttribute.o: /usr/include/string.h /usr/include/sys/prctl.h
vsSoundListenerAttribute.o: /usr/include/linux/prctl.h
vsSoundListenerAttribute.o: /usr/include/Performer/prmath.h
vsSoundListenerAttribute.o: /usr/include/math.h /usr/include/bits/huge_val.h
vsSoundListenerAttribute.o: /usr/include/bits/mathdef.h
vsSoundListenerAttribute.o: /usr/include/bits/mathcalls.h
vsSoundListenerAttribute.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/float.h
vsSoundListenerAttribute.o: /usr/include/Performer/prstats.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfLinMath.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfObject.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfMemory.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfType.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfStruct.h
vsSoundListenerAttribute.o: /usr/include/Performer/pfstats.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfBuffer.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfUpdate.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfLists.h
vsSoundListenerAttribute.o: /usr/include/g++-2/iostream.h
vsSoundListenerAttribute.o: /usr/include/g++-2/streambuf.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfFrameStats.h
vsSoundListenerAttribute.o: /usr/include/Performer/pf/pfPipe.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfVideoChannel.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfList.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfCalligraphic.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfStats.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfDispList.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfGeoState.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfState.h
vsSoundListenerAttribute.o: /usr/include/Performer/pr/pfGeoMath.h
vsSoundListenerAttribute.o: vsSoundListenerAttribute.h++
vsSoundListenerAttribute.o: ../scene/vsAttribute.h++ ../corelib/vsGlobals.h++
vsSoundListenerAttribute.o: vsSoundBuffer.h++ ../math/vsVector.h++
vsSoundListenerAttribute.o: ../math/vsMatrix.h++ ../math/vsQuat.h++
vsSoundListenerAttribute.o: ../scene/vsNode.h++
vsSoundListenerAttribute.o: ../corelib/vsGrowableArray.h++
vsSoundListenerAttribute.o: ../scene/vsAttributeList.h++
vsSoundListenerAttribute.o: ../scene/vsComponent.h++
vsSoundListenerAttribute.o: ../corelib/vsDatabaseLoader.h++
vsSoundListenerAttribute.o: /usr/include/Performer/pfdb/pfflt.h
vsSoundPipe.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/al.h
vsSoundPipe.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundPipe.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/alc.h
vsSoundPipe.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/alctypes.h
vsSoundPipe.o: vsSoundPipe.h++
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/al.h
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/alc.h
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/alctypes.h
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/alut.h
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundSample.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/aluttypes.h
vsSoundSample.o: /usr/include/stdio.h /usr/include/features.h
vsSoundSample.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
vsSoundSample.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
vsSoundSample.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
vsSoundSample.o: /usr/include/bits/types.h /usr/include/libio.h
vsSoundSample.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
vsSoundSample.o: /usr/include/getopt.h /usr/include/stdlib.h
vsSoundSample.o: /usr/include/alloca.h vsSoundSample.h++ vsSoundBuffer.h++
vsSoundSourceAttribute.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/al.h
vsSoundSourceAttribute.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundSourceAttribute.o: /ist/projects/vr2/usr/jdaly/openal/linux/include/AL/alkludge.h
vsSoundSourceAttribute.o: /ist/projects/vr2/usr/jdaly/openal/linux/include/AL/alkludgetypes.h
vsSoundSourceAttribute.o: /ist/projects/vr2/usr/jdaly/openal/include/AL/altypes.h
vsSoundSourceAttribute.o: /usr/include/sys/time.h /usr/include/features.h
vsSoundSourceAttribute.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
vsSoundSourceAttribute.o: /usr/include/time.h
vsSoundSourceAttribute.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
vsSoundSourceAttribute.o: /usr/include/bits/time.h /usr/include/bits/types.h
vsSoundSourceAttribute.o: /usr/include/sys/select.h
vsSoundSourceAttribute.o: /usr/include/bits/select.h
vsSoundSourceAttribute.o: /usr/include/bits/sigset.h /usr/include/stdio.h
vsSoundSourceAttribute.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
vsSoundSourceAttribute.o: /usr/include/libio.h /usr/include/_G_config.h
vsSoundSourceAttribute.o: /usr/include/bits/stdio_lim.h /usr/include/getopt.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfSCS.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfGroup.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfNode.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfUpdatable.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr.h
vsSoundSourceAttribute.o: /usr/include/sys/types.h /usr/include/endian.h
vsSoundSourceAttribute.o: /usr/include/bits/endian.h
vsSoundSourceAttribute.o: /usr/include/sys/sysmacros.h /usr/include/unistd.h
vsSoundSourceAttribute.o: /usr/include/bits/posix_opt.h
vsSoundSourceAttribute.o: /usr/include/bits/confname.h /usr/include/errno.h
vsSoundSourceAttribute.o: /usr/include/bits/errno.h
vsSoundSourceAttribute.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
vsSoundSourceAttribute.o: /usr/X11R6/include/X11/X.h
vsSoundSourceAttribute.o: /usr/X11R6/include/X11/Xlib.h
vsSoundSourceAttribute.o: /usr/X11R6/include/X11/Xfuncproto.h
vsSoundSourceAttribute.o: /usr/X11R6/include/X11/Xosdefs.h
vsSoundSourceAttribute.o: /usr/X11R6/include/X11/Xutil.h
vsSoundSourceAttribute.o: /usr/X11R6/include/GL/gl.h
vsSoundSourceAttribute.o: /usr/X11R6/include/GL/glx.h
vsSoundSourceAttribute.o: /usr/X11R6/include/GL/glu.h
vsSoundSourceAttribute.o: /usr/include/Performer/opengl.h
vsSoundSourceAttribute.o: /usr/include/Performer/linuxstubs.h
vsSoundSourceAttribute.o: /usr/include/Performer/image.h
vsSoundSourceAttribute.o: /usr/include/stdlib.h /usr/include/alloca.h
vsSoundSourceAttribute.o: /usr/include/string.h /usr/include/sys/prctl.h
vsSoundSourceAttribute.o: /usr/include/linux/prctl.h
vsSoundSourceAttribute.o: /usr/include/Performer/prmath.h /usr/include/math.h
vsSoundSourceAttribute.o: /usr/include/bits/huge_val.h
vsSoundSourceAttribute.o: /usr/include/bits/mathdef.h
vsSoundSourceAttribute.o: /usr/include/bits/mathcalls.h
vsSoundSourceAttribute.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/float.h
vsSoundSourceAttribute.o: /usr/include/Performer/prstats.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfLinMath.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfObject.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfMemory.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfType.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfStruct.h
vsSoundSourceAttribute.o: /usr/include/Performer/pfstats.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfBuffer.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfUpdate.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfLists.h
vsSoundSourceAttribute.o: /usr/include/g++-2/iostream.h
vsSoundSourceAttribute.o: /usr/include/g++-2/streambuf.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfFrameStats.h
vsSoundSourceAttribute.o: /usr/include/Performer/pf/pfPipe.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfVideoChannel.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfList.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfCalligraphic.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfStats.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfDispList.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfGeoState.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfState.h
vsSoundSourceAttribute.o: /usr/include/Performer/pr/pfGeoMath.h
vsSoundSourceAttribute.o: vsSoundSourceAttribute.h++ ../scene/vsAttribute.h++
vsSoundSourceAttribute.o: ../corelib/vsGlobals.h++ vsSoundBuffer.h++
vsSoundSourceAttribute.o: ../math/vsVector.h++ ../math/vsMatrix.h++
vsSoundSourceAttribute.o: ../math/vsQuat.h++ ../scene/vsNode.h++
vsSoundSourceAttribute.o: ../corelib/vsGrowableArray.h++
vsSoundSourceAttribute.o: ../scene/vsAttributeList.h++
vsSoundSourceAttribute.o: ../scene/vsComponent.h++
vsSoundSourceAttribute.o: ../corelib/vsDatabaseLoader.h++
vsSoundSourceAttribute.o: /usr/include/Performer/pfdb/pfflt.h
