#!/bin/make
#======================================================================
#		makefile
#======================================================================


#----------------------------------------------------------------------
#   Notes:
#
#	To add a new file to the system, simply list its source and
#	object files immediately below, then run 'make dep' --- this 
#	will make the new dependencies
#

#----------------------------------------------------------------------
#                       Name of the library
#----------------------------------------------------------------------
LIBNAME = libvsInput.a

#----------------------------------------------------------------------
#			All Source and Object files
#----------------------------------------------------------------------
SRCS = \
       vs6DInputDevice.c++ \
       vsAscensionSerialTrackingSystem.c++ \
       vsEthernetMotionStar.c++ \
       vsFastrak.c++ \
       vsFlockOfBirds.c++ \
       vsChordGloves.c++ \
       vsIS600.c++ \
       vsISTJoystickBox.c++ \
       vsInputAxis.c++ \
       vsInputButton.c++ \
       vsInputDevice.c++ \
       vsInputSystem.c++ \
       vsJoystick.c++ \
       vsJoystickBox.c++ \
       vsKeyboard.c++ \
       vsMouse.c++ \
       vsPinchGloveBox.c++ \
       vsSerialMotionStar.c++ \
       vsSerialPort.c++ \
       vsSharedInputData.c++ \
       vsSpaceball.c++ \
       vsTrackingSystem.c++ \
       vsMotionTracker.c++ \
       vsUnwinder.c++ \
       vsWSSpaceball.c++ \
       vsWindowSystem.c++ \
       NetworkInterface.c++ \
       UDPNetworkInterface.c++ \
       UDPUnicastNetworkInterface.c++

OBJS = \
       vs6DInputDevice.o \
       vsAscensionSerialTrackingSystem.o \
       vsEthernetMotionStar.o \
       vsFastrak.o \
       vsFlockOfBirds.o \
       vsChordGloves.o \
       vsInputAxis.o \
       vsInputButton.o \
       vsInputDevice.o \
       vsInputSystem.o \
       vsIS600.o \
       vsISTJoystickBox.o \
       vsJoystick.o \
       vsJoystickBox.o \
       vsKeyboard.o \
       vsMouse.o \
       vsPinchGloveBox.o \
       vsSerialMotionStar.o \
       vsSerialPort.o \
       vsSharedInputData.o \
       vsSpaceball.o \
       vsTrackingSystem.o \
       vsMotionTracker.o \
       vsUnwinder.o \
       vsWSSpaceball.o \
       vsWindowSystem.o \
       NetworkInterface.o \
       UDPNetworkInterface.o \
       UDPUnicastNetworkInterface.o

#----------------------------------------------------------------------
#			Compiler settings
#----------------------------------------------------------------------
CC = cc
CXX = CC
AR = ar
CFLAGS = -g -DIRIX64 -xansi -n32 -mips3 -DSGI $(INCS)
CXXFLAGS = -g -DIRIX64 -xansi -n32 -mips3 -DSGI $(INCS)
ARFLAGS = -rulc

#----------------------------------------------------------------------
#			Include file directories
#----------------------------------------------------------------------
INCS = \
       -I../corelib \
       -I../scene \
       -I../math

#----------------------------------------------------------------------
#			Default target
#----------------------------------------------------------------------
all: $(LIBNAME)

#----------------------------------------------------------------------
#			Library archive rules
#----------------------------------------------------------------------
$(LIBNAME): $(OBJS)
	ar $(ARFLAGS) $(LIBNAME) $(OBJS)

#----------------------------------------------------------------------
#			Inference Rules
#----------------------------------------------------------------------
.c++.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

.c.o:
	$(CXX) $(CXXFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f core
	rm -f $(LIBNAME)
	rm -f makefile.*.bak

#----------------------------------------------------------------------
#			This is the dependency update rule
#----------------------------------------------------------------------
dep: depend
depend:
	makedepend -f makefile.IRIX64 -- $(CFLAGS) $(INCS) -- $(SRCS)

