#!/bin/sh

# Make a config directory if one doesn't exist
if ! test -d config ; then 
    mkdir config
fi

# Scan configure.ac and generate aclocal.m4
aclocal-1.6 -I config

# Scan configure.ac and generate config.h.in
autoheader

# Run automake to generate makefile.in files from the makefile.am files
# We're using automake 1.6 because 1.9 doesn't seem to like the conditional
# test directory mentioned in the configure.ac file, even though the docs
# seem to suggest it should.
automake-1.6 --foreign --add-missing --copy

# Run autoconf to generate the configure script
autoconf
